version: '3.4'

networks:
    web:
        external: true
    internal:
        external: false

services:
    app:
        build:
            context: .
            target: app
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - MAILER_URL=${MAILER_URL}
        depends_on:
            - mysql
        networks:
            - web
            - internal
        volumes:
            - .:/app
        labels:
            - traefik.backend=${TRAEFIK_BACKEND}
            - traefik.frontend.rule=Host:${TRAEFIK_FRONTEND}
            - traefik.port=80
            - traefik.docker.network=${TRAEFIK_DOCKER_NETWORK}
    mysql:
        build:
            context: docker
            dockerfile: MysqlDockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - internal
        labels:
            - traefik.enable=false

    adminer:
        image: adminer:4.6.3-standalone
        labels:
            - traefik.backend=adminer.${TRAEFIK_BACKEND}
            - traefik.frontend.rule=Host:adminer-${TRAEFIK_FRONTEND}
            - traefik.port=8080
            - traefik.docker.network=${TRAEFIK_DOCKER_NETWORK}
        networks:
            - internal
            - web
        depends_on:
            - mysql